# toml-docs-start lang-main
[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [en.params.head]
        tagline = "Home"
    [en.params.feature]
        link = "about"
        caption = "Know more"
    [en.params.footer]
        socialTitle = "Contact me"
        socialCaption = "I'm always down to chat about something interesting!"
# toml-docs-end lang-param