[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[main]]
  name = "Eye Tracker Project"
  pageRef = "/projects/eye-project/"
  parent = "Projects"
  weight = 1

[[main]]
  name = "Deep Fake Project"
  pageRef = "/projects/deep-fake-project/"
  parent = "Projects"
  weight = 2

[[main]]
  name = "Dark Image Project"
  pageRef = "/projects/dark-image-project/"
  parent = "Projects"
  weight = 3

[[main]]
  name = "Enhance Image project"
  pageRef = "/projects/enhance-project/"
  parent = "Projects"
  weight = 4

[[main]]
  name = "Certificates"
  pageRef = "/certificates/"
  weight = 40


[[main]]
  name = "Tags"
  pageRef = "/tags/"
  weight = 50

[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://in.linkedin.com/in/shravan-bhat"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/pseudou"
  weight = 30

[[social]]
  name = "Gmail"
  pre = "<i class=\"fa-solid fa-envelope fa-2x\"></i>"
  url = "mailto:shravanbhat0@gmail.com"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Eye Tracker Project"
  pageRef = "/projects/eye-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Deep Fake Project"
  pageRef = "/projects/deep-fake-project/"
  parent = "Projects"
  weight = 2

[[sample]]
  name = "Dark Image Project"
  pageRef = "/projects/dark-image-project/"
  parent = "Projects"
  weight = 3


[[sample]]
  name = "Enhance Image Project"
  pageRef = "/projects/enhance-project/"
  parent = "Projects"
  weight = 4

[[sample]]
  name = "Certificates"
  pageRef = "/certificates/"
  weight = 30

# toml-docs-end sample-navigation